export const TYPES = {
  ADD_TO_CART: "ADD_TO_CART",
  REMOVE_ONE_FROM_PRODUCT: "REMOVE_ONE_FROM_CART",
  REMOVE_ALL_FROM_PRODUCT: "REMOVE_ALL_FROM_PRODUCT",
  CLEAR_CART: "CLEAR_CART",
  TOTAL_CART: "TOTAL_CART",
};
