const colorProd1 = "#FEF200";
const colorProd2 = "#69Fe00";

const colorProd3 = "#00A3E8";
const colorProd4 = "#2349c5";

const colorCat1 = `linear-gradient(135deg, ${colorProd1} 50%,${colorProd2} 50%)`;
const colorCat2 = `linear-gradient(135deg, ${colorProd3} 50%,${colorProd4} 50%)`;

export const products = [
  {
    id: 1,
    name: "Galleta redonda con mermelada de durazno",
    category: "Galletas de mantequilla",
    type: "Galleta",
    subcategory: "Galletas con mermelada",
    price: 100455,
    shape: "Redonda",
    flavor: "Durazno",
    servings: 1,
    measurements: {
      length: 6,
      width: 6,
      height: 1,
    },
    size: "Grande",
    quantity: "Individual",
    ingredients: [
      "Harina",
      "Azúcar",
      "Mantequilla",
      "Huevo",
      "Extracto de vainilla",
      "Azúcar pulverizada",
      "Durazno",
    ],
    image:
      "https://drive.google.com/uc?export=view&id=1h6gSdd2ZjOWjiqnPZJHhRXF06FfZdr_H",
    color: colorProd2,
  },
  {
    id: 2,
    name: "Galleta corazón con mermelada de durazno",
    category: "Galletas de mantequilla",
    type: "Galleta",
    subcategory: "Galletas con mermelada",
    price: 8900,
    shape: "Corazón",
    flavor: "Durazno",
    servings: 1,
    measurements: {
      length: 7.5,
      width: 7,
      height: 1,
    },
    size: "Grande",
    quantity: "Individual",
    ingredients: [
      "Harina",
      "Azúcar",
      "Mantequilla",
      "Huevo",
      "Extracto de vainilla",
      "Azúcar pulverizada",
      "Durazno",
    ],
    image:
      "https://drive.google.com/uc?export=view&id=1-h2Z4r9LfW428gMx_vcHxzAAn3BUoh7B",
    color: colorProd2,
  },
  {
    id: 3,
    name: "Galleta corazón con mermelada de mora",
    category: "Galletas de mantequilla",
    type: "Galleta",
    subcategory: "Galletas con mermelada",
    price: 1200,
    shape: "Corazón",
    flavor: "Mora",
    servings: 1,
    measurements: {
      length: 7.5,
      width: 7,
      height: 1,
    },
    size: "Grande",
    quantity: "Individual",
    ingredients: [
      "Harina",
      "Azúcar",
      "Mantequilla",
      "Huevo",
      "Extracto de vainilla",
      "Azúcar pulverizada",
      "Mora",
    ],
    image:
      "https://drive.google.com/uc?export=view&id=1ITc0rDt3af6-RcyHXjHe5w5SmhXRx9lv",
    color: colorProd2,
  },
  {
    id: 4,
    name: "Galleta corazón tradicional",
    category: "Galletas de mantequilla",
    type: "Galleta",
    subcategory: "Galletas tradicionales",
    price: 50,
    shape: "Corazón",
    flavor: "Natural",
    servings: 1,
    measurements: {
      length: 7.5,
      width: 7,
      height: 0.5,
    },
    size: "Grande",
    quantity: "Individual",
    ingredients: [
      "Harina",
      "Azúcar",
      "Mantequilla",
      "Huevo",
      "Extracto de vainilla",
    ],
    image:
      "https://drive.google.com/uc?export=view&id=1vWQ2jYcHI3Ys9nBkn8X0ahnofg3x_riT",
    color: colorProd1,
  },
  {
    id: 5,
    name: "Galleta redonda tradicional",
    category: "Galletas de mantequilla",
    type: "Galleta",
    subcategory: "Galletas tradicionales",
    price: 630,
    shape: "Redonda",
    flavor: "Natural",
    servings: 1,
    measurements: {
      length: 6,
      width: 6,
      height: 0.5,
    },
    size: "Grande",
    quantity: "Individual",
    ingredients: [
      "Harina",
      "Azúcar",
      "Mantequilla",
      "Huevo",
      "Extracto de vainilla",
    ],
    image:
      "https://drive.google.com/uc?export=view&id=14zjLuW7QhN5XdiLgOBNO6L___CDMfJfM",
    color: colorProd1,
  },
  {
    id: 6,
    name: "Galleta redonda con mermelada de mora",
    category: "Galletas de mantequilla",
    type: "Galleta",
    subcategory: "Galletas con mermelada",
    price: 520,
    shape: "Redonda",
    flavor: "Mora",
    servings: 1,
    measurements: {
      length: 6,
      width: 6,
      height: 1,
    },
    size: "Grande",
    quantity: "Individual",
    ingredients: [
      "Harina",
      "Azúcar",
      "Mantequilla",
      "Huevo",
      "Extracto de vainilla",
      "Azúcar pulverizada",
      "Mora",
    ],
    image:
      "https://drive.google.com/uc?export=view&id=1uE4kHbiWsUnYbu9pbzzXWQLY0Z71_PAN",
    color: colorProd2,
  },
  {
    id: 7,
    name: "Muffin grande de banano",
    category: "Muffins y panes de banano",
    type: "Muffin",
    subcategory: "Muffins de banano",
    price: 1000,
    shape: "Tradicional",
    flavor: "Banano",
    servings: 1,
    measurements: {
      length: 9,
      width: 9,
      height: 6,
    },
    size: "Grande",
    quantity: "Individual",
    ingredients: [
      "Harina",
      "Azúcar",
      "Mantequilla",
      "Banano",
      "Huevo",
      "Polvo de hornear",
      "Canela",
      "Sal",
      "Aceite vgetal",
      "Extracto de vainilla",
    ],
    image:
      "https://drive.google.com/uc?export=view&id=1M5XLyFQvB_Mc8Geda9brZzI5GdNpDXex",
    color: colorProd3,
  },
  {
    id: 8,
    name: "Muffin pequeño de banano",
    category: "Muffins y panes de banano",
    type: "Muffin",
    subcategory: "Muffins de banano",
    price: 1500,
    shape: "Tradicional",
    flavor: "Banano",
    servings: 1,
    measurements: {
      length: 9,
      width: 9,
      height: 6,
    },
    size: "Pequeño",
    quantity: "Individual",
    ingredients: [
      "Harina",
      "Azúcar",
      "Mantequilla",
      "Banano",
      "Huevo",
      "Polvo de hornear",
      "Canela",
      "Sal",
      "Aceite vgetal",
      "Extracto de vainilla",
    ],
    image:
      "https://drive.google.com/uc?export=view&id=1D4JgsYlP3apYStIcKkOe9yx6ATVcFG5k",
    color: colorProd3,
  },
  {
    id: 9,
    name: "Muffin pequeño de banano con nueces",
    category: "Muffins y panes de banano",
    type: "Muffin",
    subcategory: "Muffins de banano",
    price: 10900,
    shape: "Tradicional",
    flavor: ["Banano", "Nuez"],
    servings: 1,
    measurements: {
      length: 7,
      width: 7,
      height: 4,
    },
    size: "Pequeño",
    quantity: "Individual",
    ingredients: [
      "Harina",
      "Azúcar",
      "Mantequilla",
      "Banano",
      "Nueces",
      "Huevo",
      "Polvo de hornear",
      "Canela",
      "Sal",
      "Aceite vgetal",
      "Extracto de vainilla",
    ],
    image:
      "https://drive.google.com/uc?export=view&id=1WAr_vVG84Svp5f9NwURyZxhGAcVlj2wc",
    color: colorProd3,
  },
  {
    id: 10,
    name: "Muffin grande de banano con nueces",
    category: "Muffins y panes de banano",
    type: "Muffin",
    subcategory: "Muffins de banano",
    price: 10,
    shape: "Tradicional",
    flavor: ["Banano", "Nuez"],
    servings: 1,
    measurements: {
      length: 9,
      width: 9,
      height: 6,
    },
    size: "Grande",
    quantity: "Individual",
    ingredients: [
      "Harina",
      "Azúcar",
      "Mantequilla",
      "Banano",
      "Nueces",
      "Huevo",
      "Polvo de hornear",
      "Canela",
      "Sal",
      "Aceite vgetal",
      "Extracto de vainilla",
    ],
    image:
      "https://drive.google.com/uc?export=view&id=1Xn1r5WD00Tq55PbwaPAyF2krF24jKcH4",
    color: colorProd3,
  },
  {
    id: 11,
    name: "Pan de banano con nueces en bandeja",
    category: "Muffins y panes de banano",
    type: "Pan",
    subcategory: "Panes de banano",
    price: 1560,
    shape: "Rectangular",
    flavor: ["Banano", "Nuez"],
    servings: 10,
    measurements: {
      length: 30,
      width: 20,
      height: 4,
    },
    size: "Grande",
    quantity: "Individual",
    ingredients: [
      "Harina",
      "Azúcar",
      "Mantequilla",
      "Banano",
      "Nueces",
      "Huevo",
      "Polvo de hornear",
      "Canela",
      "Sal",
      "Aceite vgetal",
      "Extracto de vainilla",
    ],
    image:
      "https://drive.google.com/uc?export=view&id=1lsTFMClRqlJcs0pvwHlb8V8RpTGxk8gT",
    color: colorProd4,
  },
  {
    id: 12,
    name: "Pan de banano con nueces en molde",
    category: "Muffins y panes de banano",
    type: "Pan",
    subcategory: "Panes de banano",
    price: 5730,
    shape: "Molde",
    flavor: ["Banano", "Nuez"],
    servings: 10,
    measurements: {
      length: 25,
      width: 11,
      height: 7,
    },
    size: "Grande",
    quantity: "Individual",
    ingredients: [
      "Harina",
      "Azúcar",
      "Mantequilla",
      "Banano",
      "Nueces",
      "Huevo",
      "Polvo de hornear",
      "Canela",
      "Sal",
      "Aceite vgetal",
      "Extracto de vainilla",
    ],
    image:
      "https://drive.google.com/uc?export=view&id=1EYregztGNQ3itvmDNPkeWAlqTT0gJI-1",
    color: colorProd4,
  },
  {
    id: 13,
    name: "Pan de banano en bandeja",
    category: "Muffins y panes de banano",
    type: "Pan",
    subcategory: "Panes de banano",
    price: 1540,
    shape: "Rectangular",
    flavor: "Banano",
    servings: 10,
    measurements: {
      length: 25,
      width: 11,
      height: 7,
    },
    size: "Grande",
    quantity: "Individual",
    ingredients: [
      "Harina",
      "Azúcar",
      "Mantequilla",
      "Banano",
      "Huevo",
      "Polvo de hornear",
      "Canela",
      "Sal",
      "Aceite vgetal",
      "Extracto de vainilla",
    ],
    image:
      "https://drive.google.com/uc?export=view&id=1FEy-oPYS-utfej2AJSw2amYBqOt85KnO",
    color: colorProd4,
  },
  {
    id: 14,
    name: "Pan de banano en molde",
    category: "Muffins y panes de banano",
    type: "Pan",
    subcategory: "Panes de banano",
    price: 16000,
    shape: "Molde",
    flavor: "Banano",
    servings: 10,
    measurements: {
      length: 25,
      width: 11,
      height: 7,
    },
    size: "Grande",
    quantity: "Individual",
    ingredients: [
      "Harina",
      "Azúcar",
      "Mantequilla",
      "Banano",
      "Huevo",
      "Polvo de hornear",
      "Canela",
      "Sal",
      "Aceite vgetal",
      "Extracto de vainilla",
    ],
    image:
      "https://drive.google.com/uc?export=view&id=19POJQXU4RbXGtCQj1cMGPsC6jD0RTmXz",
    color: colorProd4,
  },
  {
    id: 15,
    name: "Paquete de galletas redondas tradicionales",
    category: "Galletas de mantequilla",
    type: "Galleta",
    subcategory: "Galletas tradicionales",
    price: 1850,
    shape: "Redonda",
    flavor: "Natural",
    servings: 10,
    measurements: {
      length: 3,
      width: 3,
      height: 0.5,
    },
    size: "Pequeño",
    quantity: "Paquete",
    ingredients: [
      "Harina",
      "Azúcar",
      "Mantequilla",
      "Huevo",
      "Extracto de vainilla",
    ],
    image:
      "https://drive.google.com/uc?export=view&id=1A7ml7kRcJz0g0Doc7oraEKcztyOSc7M4",
    color: colorProd1,
  },
  {
    id: 16,
    name: "Paquete de galletas corazón tradicionales",
    category: "Galletas de mantequilla",
    type: "Galleta",
    subcategory: "Galletas tradicionales",
    price: 12545,
    shape: "Corazón",
    flavor: "Natural",
    servings: 10,
    measurements: {
      length: 3.5,
      width: 4,
      height: 0.5,
    },
    size: "Pequeño",
    quantity: "Paquete",
    ingredients: ["Harina", "Azúcar"],
    image:
      "https://drive.google.com/uc?export=view&id=19iDH7vUxKdpRX2apO3IHP7thxp5mhElE",
    color: colorProd1,
  },
];

export const categories = [
  {
    id: "c1",
    name: "Galletas de mantequilla",
    url: "https://drive.google.com/uc?export=view&id=1mvyqP6mZMlU9yq16wuLKjid0PK7bjPg8",
    color: colorCat1,
  },
  {
    id: "c2",
    name: "Muffins y panes de banano",
    url: "https://drive.google.com/uc?export=view&id=1nZbwJonf-S21mIlwJtL5W6Ha5T8mFd8Q",
    color: colorCat2,
  },
];

export const subcategory1 = [
  {
    id: "c11",
    name: "Galletas tradicionales",
    url: "https://drive.google.com/uc?export=view&id=1uv06aoe3TB-e1bX9zy3VGPFS1wpQKh-N",
    color: colorProd1,
  },
  {
    id: "c12",
    name: "Galletas con mermelada",
    url: "https://drive.google.com/uc?export=view&id=1DpZPOLnkr4_Q09CxCqWjcfYTaKhhBwH4",
    color: colorProd2,
  },
];

export const subcategory2 = [
  {
    id: "c21",
    name: "Muffins de banano",
    url: "https://drive.google.com/uc?export=view&id=1l7FoTLpmVwPGYGkBnpOKm1miQ0_NzhU2",
    color: colorProd3,
  },
  {
    id: "c22",
    name: "Panes de banano",
    url: "https://drive.google.com/uc?export=view&id=1B4K4IL7SN_WaX38qH7GAbcY4RS0JILAN",
    color: colorProd4,
  },
];

export const galery = [
  {
    id: 1,
    title: "Nuestros productos",
    url: "https://drive.google.com/uc?export=view&id=1RYG9fNYeik3bhRSgA429X8h8Hfp7AIfS",
    active: true,
  },
  {
    id: 2,
    title: "Galletas tradicionales redondas",
    url: "https://drive.google.com/uc?export=view&id=1P3_rGf9F2nQZZXgpK40S5poTCZMRFeL9",
    active: false,
  },
  {
    id: 3,
    title: "Galletas y muffins",
    url: "https://drive.google.com/uc?export=view&id=1hYKvEjcoapy1i3A3M76KKoisEmA60h-3",
    active: false,
  },

  {
    id: 4,
    title: "Galletas tradicionales corazón",
    url: "https://drive.google.com/uc?export=view&id=1rF64SCqjArODYjwVqtuk4whfLnr0axxl",
    active: false,
  },
];
