const p1 = "#FEF200";
const p2 = "#69Fe00";

const p3 = "#00A3E8";
const p4 = "#2349c5";

const c1 = `linear-gradient(135deg, ${p1} 50%,${p2} 50%)`;
const c2 = `linear-gradient(135deg, ${p3} 50%,${p4} 50%)`;

export const products = [
  {
    id: 1,
    name: "Galleta redonda con mermelada de durazno",
    category: "Galletas de mantequilla",
    type: "Galleta",
    subcategory: "con mermelada",
    price: 1000,
    shape: "Redonda",
    flavor: "Durazno",
    servings: 1,
    measurements: {
      length: 6,
      width: 6,
      height: 1,
    },
    size: "Grande",
    quantity: "Individual",
    ingredients: ["Harina", "Azúcar"],
    image:
      "https://drive.google.com/uc?export=view&id=1N8CbwWV36OjOdckfanTGw7oKGzxVXBv5",
    color: p2,
  },
  {
    id: 2,
    name: "Galleta corazón con mermelada de durazno",
    category: "Galletas de mantequilla",
    type: "Galleta",
    subcategory: "con mermelada",
    price: 1000,
    shape: "Corazón",
    flavor: "Durazno",
    servings: 1,
    measurements: {
      length: 7.5,
      width: 7,
      height: 1,
    },
    size: "Grande",
    quantity: "Individual",
    ingredients: ["Harina", "Azúcar"],
    image:
      "https://drive.google.com/uc?export=view&id=1N8CbwWV36OjOdckfanTGw7oKGzxVXBv5",
    color: p2,
  },
  {
    id: 3,
    name: "Galleta corazón con mermelada de mora",
    category: "Galletas de mantequilla",
    type: "Galleta",
    subcategory: "con mermelada",
    price: 1000,
    shape: "Corazón",
    flavor: "Mora",
    servings: 1,
    measurements: {
      length: 7.5,
      width: 7,
      height: 1,
    },
    size: "Grande",
    quantity: "Individual",
    ingredients: ["Harina", "Azúcar"],
    image:
      "https://drive.google.com/uc?export=view&id=1N8CbwWV36OjOdckfanTGw7oKGzxVXBv5",
    color: p2,
  },
  {
    id: 4,
    name: "Galleta corazón tradicional",
    category: "Galletas de mantequilla",
    type: "Galleta",
    subcategory: "tradicional",
    price: 1000,
    shape: "Corazón",
    flavor: "",
    servings: 1,
    measurements: {
      length: 7.5,
      width: 7,
      height: 0.5,
    },
    size: "Grande",
    quantity: "Individual",
    ingredients: ["Harina", "Azúcar"],
    image:
      "https://drive.google.com/uc?export=view&id=1N8CbwWV36OjOdckfanTGw7oKGzxVXBv5",
    color: p1,
  },
  {
    id: 5,
    name: "Galleta redonda tradicional",
    category: "Galletas de mantequilla",
    type: "Galleta",
    subcategory: "tradicional",
    price: 1000,
    shape: "Redonda",
    flavor: "",
    servings: 1,
    measurements: {
      length: 6,
      width: 6,
      height: 0.5,
    },
    size: "Grande",
    quantity: "Individual",
    ingredients: ["Harina", "Azúcar"],
    image:
      "https://drive.google.com/uc?export=view&id=1N8CbwWV36OjOdckfanTGw7oKGzxVXBv5",
    color: p1,
  },
  {
    id: 6,
    name: "Galleta redonda con mermelada de mora",
    category: "Galletas de mantequilla",
    type: "Galleta",
    subcategory: "con mermelada",
    price: 1000,
    shape: "Redonda",
    flavor: "Mora",
    servings: 1,
    measurements: {
      length: 6,
      width: 6,
      height: 1,
    },
    size: "Grande",
    quantity: "Individual",
    ingredients: ["Harina", "Azúcar"],
    image:
      "https://drive.google.com/uc?export=view&id=1N8CbwWV36OjOdckfanTGw7oKGzxVXBv5",
    color: p2,
  },
  {
    id: 7,
    name: "Muffin grande de banano",
    category: "Muffins y panes de banano",
    type: "Muffin",
    subcategory: "Muffins de banano",
    price: 1000,
    shape: "",
    flavor: "Banano",
    servings: 1,
    measurements: {
      length: 9,
      width: 9,
      height: 6,
    },
    size: "Grande",
    quantity: "Individual",
    ingredients: ["Harina", "Azúcar"],
    image:
      "https://drive.google.com/uc?export=view&id=1N8CbwWV36OjOdckfanTGw7oKGzxVXBv5",
    color: p3,
  },
  {
    id: 8,
    name: "Muffin pequeño de banano",
    category: "Muffins y panes de banano",
    type: "Muffin",
    subcategory: "Muffins de banano",
    price: 1000,
    shape: "",
    flavor: "Banano",
    servings: 1,
    measurements: {
      length: 9,
      width: 9,
      height: 6,
    },
    size: "Pequeño",
    quantity: "Individual",
    ingredients: ["Harina", "Azúcar"],
    image:
      "https://drive.google.com/uc?export=view&id=1N8CbwWV36OjOdckfanTGw7oKGzxVXBv5",
    color: p3,
  },
  {
    id: 9,
    name: "Muffin pequeño de banano con nueces",
    category: "Muffins y panes de banano",
    type: "Muffin",
    subcategory: "Muffins de banano",
    price: 1000,
    shape: "",
    flavor: ["Banano", "Nuez"],
    servings: 1,
    measurements: {
      length: 7,
      width: 7,
      height: 4,
    },
    size: "Pequeño",
    quantity: "Individual",
    ingredients: ["Harina", "Azúcar"],
    image:
      "https://drive.google.com/uc?export=view&id=1N8CbwWV36OjOdckfanTGw7oKGzxVXBv5",
    color: p3,
  },
  {
    id: 10,
    name: "Muffin grande de banano con nueces",
    category: "Muffins y panes de banano",
    type: "Muffin",
    subcategory: "Muffins de banano",
    price: 1000,
    shape: "",
    flavor: ["Banano", "Nuez"],
    servings: 1,
    measurements: {
      length: 9,
      width: 9,
      height: 6,
    },
    size: "Grande",
    quantity: "Individual",
    ingredients: ["Harina", "Azúcar"],
    image:
      "https://drive.google.com/uc?export=view&id=1N8CbwWV36OjOdckfanTGw7oKGzxVXBv5",
    color: p3,
  },
  {
    id: 11,
    name: "Pan de banano con nueces en bandeja",
    category: "Muffins y panes de banano",
    type: "Pan",
    subcategory: "Panes de banano",
    price: 1000,
    shape: "",
    flavor: ["Banano", "Nuez"],
    servings: 10,
    measurements: {
      length: 30,
      width: 20,
      height: 4,
    },
    size: "Grande",
    quantity: "Individual",
    ingredients: ["Harina", "Azúcar"],
    image:
      "https://drive.google.com/uc?export=view&id=1N8CbwWV36OjOdckfanTGw7oKGzxVXBv5",
    color: p4,
  },
  {
    id: 12,
    name: "Pan de banano con nueces en molde",
    category: "Muffins y panes de banano",
    type: "Pan",
    subcategory: "Panes de banano",
    price: 5730,
    shape: "",
    flavor: ["Banano", "Nuez"],
    servings: 10,
    measurements: {
      length: 25,
      width: 11,
      height: 7,
    },
    size: "Grande",
    quantity: "Individual",
    ingredients: ["Harina", "Azúcar"],
    image:
      "https://drive.google.com/uc?export=view&id=1N8CbwWV36OjOdckfanTGw7oKGzxVXBv5",
    color: p4,
  },
  {
    id: 13,
    name: "Pan de banano en bandeja",
    category: "Muffins y panes de banano",
    type: "Pan",
    subcategory: "Panes de banano",
    price: 1540,
    shape: "",
    flavor: "Banano",
    servings: 10,
    measurements: {
      length: 25,
      width: 11,
      height: 7,
    },
    size: "Grande",
    quantity: "Individual",
    ingredients: ["Harina", "Azúcar"],
    image:
      "https://drive.google.com/uc?export=view&id=1N8CbwWV36OjOdckfanTGw7oKGzxVXBv5",
    color: p4,
  },
  {
    id: 14,
    name: "Pan de banano en molde",
    category: "Muffins y panes de banano",
    type: "Pan",
    subcategory: "Panes de banano",
    price: 100,
    shape: "",
    flavor: "Banano",
    servings: 10,
    measurements: {
      length: 25,
      width: 11,
      height: 7,
    },
    size: "Grande",
    quantity: "Individual",
    ingredients: ["Harina", "Azúcar"],
    image:
      "https://drive.google.com/uc?export=view&id=1N8CbwWV36OjOdckfanTGw7oKGzxVXBv5",
    color: p4,
  },
  {
    id: 15,
    name: "Paquete de galletas redondas tradicionales",
    category: "Galletas de mantequilla",
    type: "Galleta",
    subcategory: "Galletas tradicionales",
    price: 1850,
    shape: "Redonda",
    flavor: "",
    servings: 10,
    measurements: {
      length: 3,
      width: 3,
      height: 0.5,
    },
    size: "Pequeño",
    quantity: "Paquete",
    ingredients: ["Harina", "Azúcar"],
    image:
      "https://drive.google.com/uc?export=view&id=1N8CbwWV36OjOdckfanTGw7oKGzxVXBv5",
    color: p1,
  },
  {
    id: 16,
    name: "Paquete de galletas corazón tradicionales",
    category: "Galletas de mantequilla",
    type: "Galleta",
    subcategory: "Galletas tradicionales",
    price: 12545,
    shape: "Corazón",
    flavor: "",
    servings: 10,
    measurements: {
      length: 3.5,
      width: 4,
      height: 0.5,
    },
    size: "Pequeño",
    quantity: "Paquete",
    ingredients: ["Harina", "Azúcar"],
    image:
      "https://drive.google.com/uc?export=view&id=1N8CbwWV36OjOdckfanTGw7oKGzxVXBv5",
    color: p1,
  },
];

export const categories = [
  {
    id: 1,
    name: "Galletas de mantequilla",
    url: "https://drive.google.com/uc?export=view&id=1N8CbwWV36OjOdckfanTGw7oKGzxVXBv5",
    color: c1,
  },
  {
    id: 2,
    name: "Muffins y panes de banano",
    url: "https://drive.google.com/uc?export=view&id=1g9Yz-4uz0X8frPEuZXR764O3ZPiyTyL_",
    color: c2,
  },
];
