const colorProd1 = "#FEF200";
const colorProd2 = "#69Fe00";

const colorProd3 = "#00A3E8";
const colorProd4 = "#2349c5";

const colorCat1 = `linear-gradient(135deg, ${colorProd1} 50%,${colorProd2} 50%)`;
const colorCat2 = `linear-gradient(135deg, ${colorProd3} 50%,${colorProd4} 50%)`;

export const products = [
  {
    id: 1,
    name: "Galleta redonda con mermelada de durazno",
    category: "Galletas de mantequilla",
    type: "Galleta",
    subcategory: "Galletas con mermelada",
    price: 2000,
    shape: "Redonda",
    flavor: "Durazno",
    servings: 1,
    measurements: {
      length: 6,
      width: 6,
      height: 1,
    },
    size: "Grande",
    quantity: "Individual",
    ingredients: [
      "Harina",
      "Azúcar",
      "Mantequilla",
      "Huevo",
      "Extracto de vainilla",
      "Azúcar pulverizada",
      "Durazno",
    ],
    image:
      "https://drive.google.com/uc?export=view&id=1FfBf7S80n8a-XiLs4aojCNSKdtIpzZBn",
    color: colorProd2,
  },
  {
    id: 2,
    name: "Galleta corazón con mermelada de durazno",
    category: "Galletas de mantequilla",
    type: "Galleta",
    subcategory: "Galletas con mermelada",
    price: 2000,
    shape: "Corazón",
    flavor: "Durazno",
    servings: 1,
    measurements: {
      length: 7.5,
      width: 7,
      height: 1,
    },
    size: "Grande",
    quantity: "Individual",
    ingredients: [
      "Harina",
      "Azúcar",
      "Mantequilla",
      "Huevo",
      "Extracto de vainilla",
      "Azúcar pulverizada",
      "Durazno",
    ],
    image:
      "https://drive.google.com/uc?export=view&id=1T055RythP5MrhV_bBmXs1V6Hw7pO7ElO",
    color: colorProd2,
  },
  {
    id: 3,
    name: "Galleta corazón con mermelada de mora",
    category: "Galletas de mantequilla",
    type: "Galleta",
    subcategory: "Galletas con mermelada",
    price: 2000,
    shape: "Corazón",
    flavor: "Mora",
    servings: 1,
    measurements: {
      length: 7.5,
      width: 7,
      height: 1,
    },
    size: "Grande",
    quantity: "Individual",
    ingredients: [
      "Harina",
      "Azúcar",
      "Mantequilla",
      "Huevo",
      "Extracto de vainilla",
      "Azúcar pulverizada",
      "Mora",
    ],
    image:
      "https://drive.google.com/uc?export=view&id=1pugSXgzR9jUH6fMNrv3sNyTueAXD8o3n",
    color: colorProd2,
  },
  {
    id: 4,
    name: "Galleta corazón tradicional",
    category: "Galletas de mantequilla",
    type: "Galleta",
    subcategory: "Galletas tradicionales",
    price: 1500,
    shape: "Corazón",
    flavor: "Natural",
    servings: 1,
    measurements: {
      length: 7.5,
      width: 7,
      height: 0.5,
    },
    size: "Grande",
    quantity: "Individual",
    ingredients: [
      "Harina",
      "Azúcar",
      "Mantequilla",
      "Huevo",
      "Extracto de vainilla",
    ],
    image:
      "https://drive.google.com/uc?export=view&id=1ACUwfca_V276qWZRwUqLkYuyAzg__Yjx",
    color: colorProd1,
  },
  {
    id: 5,
    name: "Galleta redonda tradicional",
    category: "Galletas de mantequilla",
    type: "Galleta",
    subcategory: "Galletas tradicionales",
    price: 1500,
    shape: "Redonda",
    flavor: "Natural",
    servings: 1,
    measurements: {
      length: 6,
      width: 6,
      height: 0.5,
    },
    size: "Grande",
    quantity: "Individual",
    ingredients: [
      "Harina",
      "Azúcar",
      "Mantequilla",
      "Huevo",
      "Extracto de vainilla",
    ],
    image:
      "https://drive.google.com/uc?export=view&id=1IfRbVP0FJNnIXXJtm0Yc2uev-N04Str_",
    color: colorProd1,
  },
  {
    id: 6,
    name: "Galleta redonda con mermelada de mora",
    category: "Galletas de mantequilla",
    type: "Galleta",
    subcategory: "Galletas con mermelada",
    price: 2000,
    shape: "Redonda",
    flavor: "Mora",
    servings: 1,
    measurements: {
      length: 6,
      width: 6,
      height: 1,
    },
    size: "Grande",
    quantity: "Individual",
    ingredients: [
      "Harina",
      "Azúcar",
      "Mantequilla",
      "Huevo",
      "Extracto de vainilla",
      "Azúcar pulverizada",
      "Mora",
    ],
    image:
      "https://drive.google.com/uc?export=view&id=1crE833FWcqEW7dwcj7fCzg0JLAZ0tYJo",
    color: colorProd2,
  },
  {
    id: 7,
    name: "Muffin grande de banano",
    category: "Muffins y panes de banano",
    type: "Muffin",
    subcategory: "Muffins de banano",
    price: 4000,
    shape: "Tradicional",
    flavor: "Banano",
    servings: 1,
    measurements: {
      length: 9,
      width: 9,
      height: 6,
    },
    size: "Grande",
    quantity: "Individual",
    ingredients: [
      "Harina",
      "Azúcar",
      "Mantequilla",
      "Banano",
      "Huevo",
      "Polvo de hornear",
      "Canela",
      "Sal",
      "Aceite vgetal",
      "Extracto de vainilla",
    ],
    image:
      "https://drive.google.com/uc?export=view&id=1fBU_ukGbIN3oPnpykb_SEkl2m2B1Mcb-",
    color: colorProd3,
  },
  {
    id: 8,
    name: "Muffin pequeño de banano",
    category: "Muffins y panes de banano",
    type: "Muffin",
    subcategory: "Muffins de banano",
    price: 2000,
    shape: "Tradicional",
    flavor: "Banano",
    servings: 1,
    measurements: {
      length: 9,
      width: 9,
      height: 6,
    },
    size: "Pequeño",
    quantity: "Individual",
    ingredients: [
      "Harina",
      "Azúcar",
      "Mantequilla",
      "Banano",
      "Huevo",
      "Polvo de hornear",
      "Canela",
      "Sal",
      "Aceite vgetal",
      "Extracto de vainilla",
    ],
    image:
      "https://drive.google.com/uc?export=view&id=1lgc2HfoFxcp8-MQzGd-n8p08UAI-nSUk",
    color: colorProd3,
  },
  {
    id: 9,
    name: "Muffin pequeño de banano con nueces",
    category: "Muffins y panes de banano",
    type: "Muffin",
    subcategory: "Muffins de banano",
    price: 2500,
    shape: "Tradicional",
    flavor: ["Banano", "Nuez"],
    servings: 1,
    measurements: {
      length: 7,
      width: 7,
      height: 4,
    },
    size: "Pequeño",
    quantity: "Individual",
    ingredients: [
      "Harina",
      "Azúcar",
      "Mantequilla",
      "Banano",
      "Nueces",
      "Huevo",
      "Polvo de hornear",
      "Canela",
      "Sal",
      "Aceite vgetal",
      "Extracto de vainilla",
    ],
    image:
      "https://drive.google.com/uc?export=view&id=1-Gocn-zJeIIyrd34Z2pxy9eOWYIvr2I7",
    color: colorProd3,
  },
  {
    id: 10,
    name: "Muffin grande de banano con nueces",
    category: "Muffins y panes de banano",
    type: "Muffin",
    subcategory: "Muffins de banano",
    price: 4500,
    shape: "Tradicional",
    flavor: ["Banano", "Nuez"],
    servings: 1,
    measurements: {
      length: 9,
      width: 9,
      height: 6,
    },
    size: "Grande",
    quantity: "Individual",
    ingredients: [
      "Harina",
      "Azúcar",
      "Mantequilla",
      "Banano",
      "Nueces",
      "Huevo",
      "Polvo de hornear",
      "Canela",
      "Sal",
      "Aceite vgetal",
      "Extracto de vainilla",
    ],
    image:
      "https://drive.google.com/uc?export=view&id=1EuSlEdna9KOxwh8HcVgPaBhjLgk2F899",
    color: colorProd3,
  },
  {
    id: 11,
    name: "Pan de banano con nueces en bandeja",
    category: "Muffins y panes de banano",
    type: "Pan",
    subcategory: "Panes de banano",
    price: 20000,
    shape: "Rectangular",
    flavor: ["Banano", "Nuez"],
    servings: 15,
    measurements: {
      length: 30,
      width: 20,
      height: 4,
    },
    size: "Grande",
    quantity: "Individual",
    ingredients: [
      "Harina",
      "Azúcar",
      "Mantequilla",
      "Banano",
      "Nueces",
      "Huevo",
      "Polvo de hornear",
      "Canela",
      "Sal",
      "Aceite vgetal",
      "Extracto de vainilla",
    ],
    image:
      "https://drive.google.com/uc?export=view&id=1cEGtYjeLJHjVzaOkmjn4cK40vg6w3D5w",
    color: colorProd4,
  },
  {
    id: 12,
    name: "Pan de banano con nueces en molde",
    category: "Muffins y panes de banano",
    type: "Pan",
    subcategory: "Panes de banano",
    price: 20000,
    shape: "Molde",
    flavor: ["Banano", "Nuez"],
    servings: 15,
    measurements: {
      length: 25,
      width: 11,
      height: 7,
    },
    size: "Grande",
    quantity: "Individual",
    ingredients: [
      "Harina",
      "Azúcar",
      "Mantequilla",
      "Banano",
      "Nueces",
      "Huevo",
      "Polvo de hornear",
      "Canela",
      "Sal",
      "Aceite vgetal",
      "Extracto de vainilla",
    ],
    image:
      "https://drive.google.com/uc?export=view&id=1s4yBLjHc9QveR3wlij28rKSl_JWKv5Cw",
    color: colorProd4,
  },
  {
    id: 13,
    name: "Pan de banano en bandeja",
    category: "Muffins y panes de banano",
    type: "Pan",
    subcategory: "Panes de banano",
    price: 18000,
    shape: "Rectangular",
    flavor: "Banano",
    servings: 10,
    measurements: {
      length: 25,
      width: 11,
      height: 7,
    },
    size: "Grande",
    quantity: "Individual",
    ingredients: [
      "Harina",
      "Azúcar",
      "Mantequilla",
      "Banano",
      "Huevo",
      "Polvo de hornear",
      "Canela",
      "Sal",
      "Aceite vgetal",
      "Extracto de vainilla",
    ],
    image:
      "https://drive.google.com/uc?export=view&id=1a6Djg8P0Y24FN-eH0PcahgMi-OKtjFgy",
    color: colorProd4,
  },
  {
    id: 14,
    name: "Pan de banano en molde",
    category: "Muffins y panes de banano",
    type: "Pan",
    subcategory: "Panes de banano",
    price: 18000,
    shape: "Molde",
    flavor: "Banano",
    servings: 10,
    measurements: {
      length: 25,
      width: 11,
      height: 7,
    },
    size: "Grande",
    quantity: "Individual",
    ingredients: [
      "Harina",
      "Azúcar",
      "Mantequilla",
      "Banano",
      "Huevo",
      "Polvo de hornear",
      "Canela",
      "Sal",
      "Aceite vgetal",
      "Extracto de vainilla",
    ],
    image:
      "https://drive.google.com/uc?export=view&id=1wtSyM_moxPy1auwgnBWRSV2IYWMZAcyk",
    color: colorProd4,
  },
  {
    id: 15,
    name: "Paquete de galletas redondas tradicionales",
    category: "Galletas de mantequilla",
    type: "Galleta",
    subcategory: "Galletas tradicionales",
    price: 3500,
    shape: "Redonda",
    flavor: "Natural",
    servings: 10,
    measurements: {
      length: 3,
      width: 3,
      height: 0.5,
    },
    size: "Pequeño",
    quantity: "Paquete",
    ingredients: [
      "Harina",
      "Azúcar",
      "Mantequilla",
      "Huevo",
      "Extracto de vainilla",
    ],
    image:
      "https://drive.google.com/uc?export=view&id=1ynukIwnKPA7c1qGsNB2JoCMAaGtEBvO-",
    color: colorProd1,
  },
  {
    id: 16,
    name: "Paquete de galletas corazón tradicionales",
    category: "Galletas de mantequilla",
    type: "Galleta",
    subcategory: "Galletas tradicionales",
    price: 3500,
    shape: "Corazón",
    flavor: "Natural",
    servings: 10,
    measurements: {
      length: 3.5,
      width: 4,
      height: 0.5,
    },
    size: "Pequeño",
    quantity: "Paquete",
    ingredients: ["Harina", "Azúcar"],
    image:
      "https://drive.google.com/uc?export=view&id=1LGDu3GyzMA8Fo_Vuqi4TrDePytJyKh_V",
    color: colorProd1,
  },
];

export const categories = [
  {
    id: "c1",
    name: "Galletas de mantequilla",
    url: "https://drive.google.com/uc?export=view&id=1NoZ7idFQgKOxGm-EB2U-2aT9CKBUtNqX",
    color: colorCat1,
  },
  {
    id: "c2",
    name: "Muffins y panes de banano",
    url: "https://drive.google.com/uc?export=view&id=1vnSW6OS35GhHTKoktHgGT7DBcOLzJzXD",
    color: colorCat2,
  },
];

export const subcategory1 = [
  {
    id: "c11",
    name: "Galletas tradicionales",
    url: "https://drive.google.com/uc?export=view&id=1Iqs_aPf5lj7dAAurj0pOJIrzeASplSOs",
    color: colorProd1,
  },
  {
    id: "c12",
    name: "Galletas con mermelada",
    url: "https://drive.google.com/uc?export=view&id=1y4QQbg4VIM0bk-LFT2XQdKCmciGSDaxR",
    color: colorProd2,
  },
];

export const subcategory2 = [
  {
    id: "c21",
    name: "Muffins de banano",
    url: "https://drive.google.com/uc?export=view&id=1p063eUDt-xHjBCjeHpLy5SyXkImtqUym",
    color: colorProd3,
  },
  {
    id: "c22",
    name: "Panes de banano",
    url: "https://drive.google.com/uc?export=view&id=11KQtMhSDDcVUXVTORwwgmDtd1vW8v85G",
    color: colorProd4,
  },
];

export const galery = [
  {
    id: 1,
    title: "Nuestros productos",
    url: "https://drive.google.com/uc?export=view&id=1pbYqL6UccOEpnTfWy15roWt9CPkMj7ky",
    active: true,
  },
  {
    id: 2,
    title: "Galletas tradicionales redondas",
    url: "https://drive.google.com/uc?export=view&id=1Gdf1iIIoMuStnM3I9FIxYR8nWGBVhuMH",
    active: false,
  },
  {
    id: 3,
    title: "Galletas y muffins",
    url: "https://drive.google.com/uc?export=view&id=1nsg3nISbmmUWG6TQBZt5z_zdOVDm5wHw",
    active: false,
  },

  {
    id: 4,
    title: "Galletas tradicionales corazón",
    url: "https://drive.google.com/uc?export=view&id=17bZuZHal3PIG4V4XEkUsbv4ekaNJ5eHv",
    active: false,
  },
];
